from imdash.components.view_2d.annotation import Annotation2DComp
from imdash.components.view_2d.bars import Bars2DComp
from imdash.components.view_2d.circle import Circle2DComp
from imdash.components.view_2d.drag_line import DragLine2DComp
from imdash.components.view_2d.drag_point import DragPoint2DComp
from imdash.components.view_2d.history import History2DComp
from imdash.components.view_2d.hot_key import Hotkey2DComp
from imdash.components.view_2d.image import Image2DComp
from imdash.components.view_2d.inf_line import InfLine2DComp
from imdash.components.view_2d.point_cloud import PointCloud2DComp
from imdash.components.view_2d.point_cloud_proj import PointCloudProj2DComp
from imdash.components.view_2d.rectangle import Rectangle2DComp
from imdash.components.view_2d.value import Value2DComp
